version: 2
jobs:
  build:
    working_directory: ~/planning-poker
    docker: 
      - image: circleci/node:9-jessie-browsers
    steps:
      - checkout
      - run:
          name: Install npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm test